AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  corona-tracking

  Sample SAM Template for corona-tracking
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15


Resources:
  GeneralPuppeteerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: GeneralPuppeteerLayer
        Description: Hold Puppeteer library and node modules
        ContentUri: layers/puppeteer/
        CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  
  BrowserAndUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: BrowserAndUtilsLayer
        Description: Holds helper functions for application
        ContentUri: hello-world/utils/
        CompatibleRuntimes:
          - nodejs12.x
        RetentionPolicy: Delete

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 4096
      Layers:
        - !Ref GeneralPuppeteerLayer # Attach Our Chrome Layer
        - !Ref BrowserAndUtilsLayer
      Events:
        HelloWorldApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/getList/
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/api/getList/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
