version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "coronavirus-tracker-website"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hdiz0vebbxyw"
s3_prefix = "coronavirus-tracker-website"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
