AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  coronavirus-tracker-website-dev-stack
  CloudFormation Template for SAM (Dev Environment)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs14.x
    Environment:
      Variables:
        ENVIRONMENT_TYPE:
          Type: String
          Default: "Dev"
        HELLO_ENV:
          Type: String
          Default: "Covid"
    MemorySize: 128
    Timeout: 180

Resources:
  ## Covid Lambda Function ##
  CovidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/hello.handler
      Description: A simple example function for Hello Covid API
      Events:
        CovidDataAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /covid
            Method: GET

  ## Daily send email function ##
  SendDailyEmailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/email-handlers/send-daily-email.handler
      Description: Daily scheduled email sending function to subscribers
      Role: !GetAtt SendDailyEmailIamRole.Arn
      Events:
        DailyScheduleRule:
          Type: Schedule
          Properties:
            Schedule: rate(24 hours)

  # Role for Send Email function
  SendDailyEmailIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ses:*
                Resource: "*"
          PolicyName: SESFullAccess

        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
          PolicyName: AWSLambdaBasicExecutionRole

  ## Subscribe email function ##
  SubscribeEmailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/email-handlers/subscribe-email.handler
      Description: Daily scheduled email sending function to subscribers
      Events:
        SubscribeEmailAPI:
          Type: Api
          Properties:
            Path: /subscribe
            Method: POST

  # DynamoDB Email Subscription table
  EmailSubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: "Email"
          KeyType: "HASH"
        - AttributeName: "CreatedAt"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "Email"
          AttributeType: "S"
        - AttributeName: "CreatedAt"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "emailSubscription"

  # Shared layer with Lambda runtime dependencies
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: "coronavirus-tracker-website-dev-dependencies"
      Description: Node.js Runtime dependencies for Lambdas  (Dev Environment)
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain

# Created resources on AWS
Outputs:
  # Section for Covid test API
  CovidAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  CovidFunction:
    Description: "Covid Lambda Function ARN"
    Value: !GetAtt CovidFunction.Arn

  CovidFunctionIamRole:
    Description: "Implicit IAM Role created for Covid Function"
    Value: !GetAtt CovidFunctionRole.Arn

  # Section for SendDailyEmailFunction
  SendDailyEmailFunction:
    Description: "Send Email Function ARN"
    Value: !GetAtt SendDailyEmailFunction.Arn

  # Section for DynamoDB Table of Email Subscription
  EmailSubscriptionTable:
    Description: "DynamoDB's Table for Email Subscriptions"
    Value: !GetAtt EmailSubscriptionTable.Arn
